config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'homes/index'
  get 'homes/film'
  get 'homes/theater'
  get 'homes/ask'
  
 

  
  get  'films/new'
  get  '/films', to:'films#index'
  post '/films', to:'films#create'
  
  

  
  resources :users
  resources :topics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
    validates :film_name, presence: true
    validates :summary, presence: true
    validates :image, presence: true
    
    belongs_to :user
    mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  validates :password,:password_confirmation, format: { with: VALID_PASSWORD_REGEX }
    
  has_secure_password
    
  has_many :topics
  has_many :films
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all
  end
  
  def new
    @film = Film.new
  end
  
  

  def create
    @film = current_user.films.new(film_params)

    if @film.save
      redirect_to films_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def film_params
    params.require(:film).permit(:user_id, :film_name, :image, :summary)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end
  
  private
  
  def post_params
  # submitしたデータのうち、Model作成に必要なものを
  # permitの引数に指定する
  params.require(:params).permit(
    :name, :email, :message
  )
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all
  end
  
  def new
    @topic = Topic.new
  end
  

  

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  
  private
    def topic_params
      params.require(:topic).permit(:user_id, :image, :description)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
   <% end %>
     <%= yield %>
     
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE>
    <html lang='ja'>
     <head>
       <meta charset='utf-8'>
       <title>movie</title>
       <link rel="stylesheet" href="index.css">
     </head>
 
     <body>
        <div class="wrapper">
            <div id="container">
                <h1 class="text-white header-title">Movie_Life</h1>
                <h2 class="text-white header-subtitle">一味違う映画ライフを</h2>
                <div class="row">
                
                    <%= link_to '新規登録', new_user_path, class: 'btn' %>
                    <%= link_to 'ログイン', login_path,class: 'btn btn2' %>
                </div>
            </div>
        </div>
     </body>
    
    </html>

app/views/pages/login.html.erb
<!DOCTYPE>
<html lang='ja'>
 <head>
   <meta charset='utf-8'>
   <title>movie</title>
   <link rel="stylesheet" href="login.css">
 </head>
 
 <body>
   <div class="users-new-wrapper">
      <div class="container">
        <div class="row">
          <div class="users-new-container">
            <h1 class="text-center text-white">新規登録</h1>
            <%= form_for @user do |f| %>
                <div class="form-group">
                 <%= f.label :name, class: 'text-white' %>
                 <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                 <%= f.label :email, class: 'text-white' %>
                 <%= f.text_field :email, class: 'form-control' %>
                </div>
                <%= f.submit "登録", class: 'btn-block btn-white' %>
            <% end %>
            <%= link_to 'ログインはこちら', '#',class: 'text-white' %>
          </div>
         </div>
       </div>
    </div>
     
 </body>
 
 
 </html>