config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'homes/index'
  get 'homes/film'
  get 'homes/theater'
  get 'homes/ask'
  
 

  
  get  'films/new'
  get  '/films', to:'films#index'
  post '/films', to:'films#create'
  
  

  
  resources :users
  resources :topics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
    validates :film_name, presence: true
    validates :summary, presence: true
    validates :image, presence: true
    
    belongs_to :user
    mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/use.rb
class Use < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  validates :password,:password_confirmation, format: { with: VALID_PASSWORD_REGEX }
    
  has_secure_password
    
  has_many :topics
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all
  end
  
  def new
    @film = Film.new
  end
  
  

  def create
    @film = current_user.films.new(film_params)

    if @film.save
      redirect_to films_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def film_params
    params.require(:film).permit(:user_id, :film_name, :image, :summary)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end
  
  private
  
  def post_params
  # submitしたデータのうち、Model作成に必要なものを
  # permitの引数に指定する
  params.require(:params).permit(
    :name, :email, :message
  )
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to homes_index_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all
  end
  
  def new
    @topic = Topic.new
  end
  

  

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  
  private
    def topic_params
      params.require(:topic).permit(:user_id, :image, :description)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/index.html.erb
<html>
    
　 <head>
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <link href='homes.css' rel='stylesheet'>
　 </head>

  <body>
    
    <header>
        <nav>
            <ul class="clearfix">
              <li>ホーム</li>
              <li><%= link_to '作品一覧', homes_film_path %></li>
              <li><%= link_to '映画館', new_topic_path %></li>
              <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
              <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
          </ul>
        </nav>
    </header>


      <div class="film-index-wrapper">
          <div class="container">
                <% @films.each do |film| %>
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                      <div class="film-index-single">
                        <h2 class="film-author">
                          <%= film.user.name %>
                        </h2>
                        <%= image_tag film.image.url %>
                        <p class="film-text">
                          <%= film.description %>
                        </p>
                      </div>
                    </div>
                  </div>
                <% end %>
          </div>
      </div>
            
    <footer>
      <ul>
        <li>ホーム</li>
        <li><%= link_to '作品一覧', homes_film_path %></li>
        <li><%= link_to '映画館', new_topic_path %></li>
        <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
        <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
      </ul>
    
    <small>&copy; 2018 CSS Cafe</small>
    </footer>
    
    
  </body>
</html>

app/views/films/new.html.erb
 <html>
   <head>
     <link href='homes.css' rel='stylesheet'>
     <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js"></script>
   </head>
   
   <body>
     
      <header>
        <nav>
            <ul class="clearfix">
            <li><i class="fas fa-home"></i>ホーム</li>
            <li>
              <%= link_to homes_film_path do %>
                <i class="fa fa-sign-out"></i> 作品一覧
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <i class="fas fa-film"></i> 映画館
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
            <li>
              <%= link_to homes_ask_path do %>
                <i class="fas fa-envelope-open-text"></i> お問い合わせ
              <% end %>
            </li>
          </ul>
        </nav>
    </header>

    <div class="topic-new-wrapper" >
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <h1 class="text-center">Add Picture</h1>
            <%= form_for @film do |f| %>
              <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image%>
              </div>
              
              <div class="form-group">
                <%= f.label '映画名' %>
                <%= f.text_field :film_name%>
              </div>
    
              <div class="form-group">
                <%= f.label :summary %>
                <%= f.text_area :summary, class: 'form-control' %>
              </div>
    
              <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
    
            <% end %>
          </div>
        </div>
      </div>
    </div>

     
   </body>
   
 </html>
 

app/views/homes/ask.html.erb
<html>
    
　 <head>
　   　<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <link href='homes.css' rel='stylesheet'>
　 </head>

  <body>
    
   
     
    <header>
        <nav>
            <ul class="clearfix">
              <li><%= link_to 'ホーム', homes_index_path %></li>
              <li><%= link_to '作品一覧', homes_film_path %></li>
              <li><%= link_to '映画館', new_topic_path %></li>
              <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
              <li>お問い合わせ</li>
          </ul>
        </nav>
    </header>
    
   
    
     <main class="clearfix">
      
          <div class="contact">
            
            <h1>お問合せ</h1>
            <form action="#" method="post">
              <p>お名前（必須）：<br>
              <input type="text" name="name"></p>
              <p>メールアドレス：<br>
              <input type="text" name="mail"></p>
              <p>お問合せ内容：<br>
              <textarea name="comment" cols="30" rows="5"></textarea></p>
              <p><input type="submit" value="送信する" onclick="submitbtn();"></p>
            </form>
            
            <p>※FacebookのMessengerでも受け付けております。</p>
            <div class="film-button">
              <%= link_to 'こちらから', '#', { :class => "btn-square-slant" } %>
            </div>
            
          </div>
        
     
     </main>
      <!-- footer_begin -->
      <footer>
        <ul>
          <li><%= link_to 'ホーム', homes_index_path %></li>
          <li><%= link_to '作品一覧', homes_film_path %></li>
          <li><%= link_to '映画館', new_topic_path %></li>
          <li>お問い合わせ</li>    
        </ul>
      
      <small>&copy; 2018 CSS Cafe</small>
      </footer>
    </div>

  
  <script type="text/javascript">
  　　function submitbtn() {
        // 「OK」ボタン押下時
        if (confirm('内容に間違いはないですか？')) {
            alert('OK');
        }
        // 「キャンセル」ボタン押下時
        else {
            alert('キャンセル');
       　 }
  　　}
　</script>
    
  </body>
</html>

app/views/homes/film.html.erb
<html>
    
　 <head>
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <link href='homes.css' rel='stylesheet'>
　     <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
　     <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
　 </head>

  <body>
    
    <header>
        <nav>
            <ul class="clearfix">
              <li><%= link_to 'ホーム', homes_index_path %></li>
              <li>作品一覧</li>
              <li><%= link_to '映画館', new_topic_path %></li>
              <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
              <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
          </ul>
        </nav>
    </header>
    
    <main class="clearfix">
      
      <div class="film-button">
        <%= link_to '新規投稿はこちらから', films_new_path, { :class => "btn-square-slant" } %>
      </div>
      
      <div class="clearfix">
        <h2 class="films_p">人気作品</h2>
        <div class="slider">
          <div><%= image_tag 'sample1.jpg'%></div>
          <div><%= image_tag 'sample2.jpg'%></div>
          <div><%= image_tag 'sample3.jpg'%></div>
          <div><%= image_tag 'sample4.jpg'%></div>
          <div><%= image_tag 'sample5.jpg'%></div>
          <div><%= image_tag 'sample6.jpg'%></div>
        </div>
      </div> 
      
      <div class="films">
        <h2 class="films_new">新着作品</h2>
        <p>
          <img src="http://placehold.jp/300x200.png" alt="写真" class="example1">
          画像を左に配置して、
          右側にテキストを回り込ませます。
          <br clear="left">
          (映画名）
        </p>
        
      <p>
          <img src="http://placehold.jp/300x200.png" alt="写真" class="example1">
          画像を左に配置して、
          右側にテキストを回り込ませます。
          <br clear="left">
          (映画名）
      </p>
       
      </div>
      
        
    </main>
    <!-- main_end -->
    
    <!-- footer_begin -->
    <footer>
      <ul>
        <li><%= link_to 'ホーム', homes_index_path %></li>
        <li>作品一覧</li>
        <li><%= link_to '映画館', homes_theater_path %></li>
        <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
      </ul>
    
    <small>&copy; 2018 CSS Cafe</small>
    </footer>
    
  <script>
   $('.slider').slick({
     slidesToShow: 3,
     arrows:true,//スライダーの左右に「進む」「戻る」ボタンをつけるか否か
     prevArrow:'<button type="button" class="slick-prev">次へ</button>',//「戻る」ボタンのhtmlを指定
     nextArrow:'<button type="button" class="slick-next">戻る</button>',//「進む」ボタンのhtmlを指定
     autoplay: true,
     autoplaySpeed: 1500,
     centerMode: true,
   });
  </script>
    
    
  </body>
</html>

app/views/homes/index.html.erb
<html>
    
　 <head>
　     <link href='homes.css' rel='stylesheet'>
　     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
　     <!--slick記述-->
　     <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <!--slick記述-->
       <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
　     <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js"></script>
　 </head>

  <body>
    
    <header>
        <nav>
            <ul class="clearfix">
            <li><i class="fas fa-home"></i>ホーム</li>
            <li>
              <%= link_to homes_film_path do %>
                <i class="fa fa-sign-out"></i> 作品一覧
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <i class="fas fa-film"></i> 映画館
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
            <li>
              <%= link_to homes_ask_path do %>
                <i class="fas fa-envelope-open-text"></i> お問い合わせ
              <% end %>
            </li>
          </ul>
        </nav>
    </header>
    
    <main class="clearfix">
         <div id="main_image">
           <%= image_tag 'movie.jpeg', :size =>'940x350'%>
         </div>
    
         <div id="main_content">
          <section id="info">
            <h2><i class="fas fa-bell"></i>お知らせ</h2>
              <dl>
                <dt>2019年6月10日</dt>
                <dd>リニューアルオープンしました。</dd>
                <dt>2019年6月15日</dt>
                <dd>6/27（金）は設備メンテナンスのため休業いたします。</dd>
                <dt>2019年6月20日</dt>
                <dd>お盆休みも休まず営業いたします</dd>
              </dl>
          </section>
    
          <section id="campaign">
           <h2><i class="fa fa-sign-out"></i>キャンペーン情報</h2>
            <ul>
              <li>日頃の感謝を込めて、全館がいつもよりお得に！</li>
              <li>平日11時から14時までお得な割引タイムを実施中。</li>
              <li>とってもオトクな早期予約受付中。</li>
            </ul>
          </section>
        </div>
    
      <div class="clearfix">
        <!-- side_bar -->
        <aside id="side_bar">
          <ul>
    
            <li>
              <a href="#">
                <img src="http://placehold.jp/300x200.png" alt="バナー1">
              </a>
            </li>
    
            <li>
              <a href="#">
                <img src="http://placehold.jp/300x200.png" alt="バナー2">
              </a>
            </li>
    
          </ul>
        </aside>
      </div>
       
      <div class="clearfix">
        <h2>あなたへのおすすめ</h2>
        <div class="slider">
          <div><%= image_tag 'sample1.jpg'%></div>
          <div><%= image_tag 'sample2.jpg'%></div>
          <div><%= image_tag 'sample3.jpg'%></div>
          <div><%= image_tag 'sample4.jpg'%></div>
          <div><%= image_tag 'sample5.jpg'%></div>
          <div><%= image_tag 'sample6.jpg'%></div>
        </div>
      </div> 
      
      
    </main>
    <!-- main_end -->


    <!-- footer_begin -->
    <footer>
      <ul>
        <li>ホーム</li>
        <li><%= link_to '作品一覧', homes_film_path %></li>
        <li><%= link_to '映画館', new_topic_path %></li>
        <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
      </ul>
    
    <small>&copy; 2019 Movie_Life</small>
    </footer>
  
  <script>
   $('.slider').slick({
     slidesToShow: 3,
     arrows:true,//スライダーの左右に「進む」「戻る」ボタンをつけるか否か
     prevArrow:'<button type="button" class="slick-prev">戻る</button>',//「戻る」ボタンのhtmlを指定
     nextArrow:'<button type="button" class="slick-next">次へ</button>',//「進む」ボタンのhtmlを指定
     autoplay: true,
     autoplaySpeed: 1500,
     centerMode: true,
   });
  </script>
 
  </body>
</html>

app/views/topics/index.html.erb
<html>
    
　 <head>
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <link href='homes.css' rel='stylesheet'>
　 </head>

  <body>
    
    <header>
        <nav>
            <ul class="clearfix">
              <li>ホーム</li>
              <li><%= link_to '作品一覧', homes_film_path %></li>
              <li><%= link_to '映画館', new_topic_path %></li>
              <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
              <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
          </ul>
        </nav>
    </header>


      <div class="topic-index-wrapper">
          <div class="container">
                <% @topics.each do |topic| %>
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                      <div class="topic-index-single">
                        <h2 class="topic-author">
                          <%= topic.user.name %>
                        </h2>
                        <%= image_tag topic.image.url %>
                        <p class="topic-text">
                          <%= topic.description %>
                          <%= topic.description %>
                          <%= topic.description %>
                        </p>
                        
                    </div>
                  </div>
                <% end %>
          </div>
      </div>
            
    <footer>
      <ul>
        <li>ホーム</li>
        <li><%= link_to '作品一覧', homes_film_path %></li>
        <li><%= link_to '映画館', new_topic_path %></li>
        <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
        <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
      </ul>
    
    <small>&copy; 2018 CSS Cafe</small>
    </footer>
    
    
  </body>
</html>

app/views/topics/new.html.erb
<html>
    
　 <head>
　     <script src="jquery.min.js" type="text/javascript"></script>
　     <link href='homes.css' rel='stylesheet'>
　 </head>

  <body>
    
    <header>
        <nav>
            <ul class="clearfix">
              <li><%= link_to 'ホーム', homes_index_path %></li>
              <li><%= link_to '作品一覧', homes_film_path %></li>
              <li>映画館</li>
              <li><%= link_to 'ログアウト',logout_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %></li>
              <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
          </ul>
        </nav>
    </header>
    
   <div class="topic-new-wrapper" >
        <div class="container-fluid">
          <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <div class="post">
                  <h1 class="text-center">投稿画面</h1>
                  <%= form_for @topic do |f| %>
                    <div class="form-group">
                      <%= f.label '写真', {class: 'topic-name'} %>
                      <%= f.file_field :image%>
                      <p><%= f.check_box :remove_image %>画像を削除する</p>
                    </div>
                    
                    
                    <div class="form-group">
                      <%= f.label '映画館名',{class: 'topic-name'} %>
                      <%= f.text_field :description, class: 'form-control' %>
                    </div>
                    
                    <div class="form-group">
                      <%= f.label '収容人数',{class: 'topic-name'} %>
                      <%= f.text_field :description, class: 'form-control' %>
                    </div>
                    
                    <div class="form-group">
                      <%= f.label '値段',{class: 'topic-name'} %>
                      <%= f.text_field :description, class: 'form-control' %>
                    </div>
          
                    <div class="form-group">
                      <%= f.label '詳細説明',{class: 'topic-name'} %>
                      <%= f.text_area :description, class: 'form-control' %>
                    </div>
          
                    <%= f.submit '投稿', class: 'btn-1' %>
          
                  <% end %>
                </div>
              </div>
          </div>
        </div>
    </div>

    <!-- footer_begin -->
    <footer>
      <ul>
        <li><%= link_to 'ホーム', homes_index_path %></li>
        <li><%= link_to '作品一覧', homes_film_path %></li>
        <li><%= link_to '映画館', new_topic_path %></li>
        <li><%= link_to 'お問い合わせ', homes_ask_path %></li>
      </ul>
    
    <small>&copy; 2018 CSS Cafe</small>
    </footer>
    
    
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE>
<html lang='ja'>
 <head>
   <meta charset='utf-8'>
   <title>movie</title>
   <link rel="stylesheet" href="login.css">
 </head>
 
 <body>
     
   <div class="wrapper">
      <div class="container">
        <div class="row">
          
            <h1 class="text-center text-white">新規登録</h1>
            <%= form_for @user do |f| %>
                <div class="form-g">
                 <%= f.text_field :name, :placeholder => "お名前", class: 'form-c' %>
                </div>
                <div class="form-g">
                 <%= f.text_field :email, :placeholder => "メールアドレス", class: 'form-c' %>
                </div>
                
                <div class="form-g">
                    <%= f.password_field :password, :placeholder => "パスワード",class: 'form-c' %>
                </div>
                

                <%= f.submit "登録", class: 'sub' %>
            <% end %>
            <%= link_to 'ログインはこちら', login_path, class:'text-white' %>
          
         </div>
       </div>
    </div>
     
 </body>
 
 
 </html>